package DSI_Graph_Main_Controlers.TestProgramGenerator;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class tslGenerator {
    List<String> tsl;

    tslGenerator() throws UnknownHostException {
        tsl = new ArrayList<String>();
        tsl.add("// *1********* TSL file generated by Harness Design System Interface Diagram");
        tsl.add("// *2********* Date: " + LocalDateTime.now());
        tsl.add("// *3********* ComputerName: " + InetAddress.getLocalHost().getHostName());
        tsl.add("// *4********* UserName: " + System.getProperty("user.name"));
        tsl.add("// *5*********************************************************************************************************");
    }

    public List<String> getTsl(){
        tsl.add("End.");
        return tsl;
    }
    public void cleanTsl(){
        tsl.clear();
    }
    public void addConnection(String connectionName, String connectionColor, String connectionLenght, String wireArea, String connectorFrom, String moduleFrom, String connectorTo, String moduleTo){
        if (!connectorFrom.equals("") && !connectorTo.equals("")) {
            tsl.add("TestConnection('" + connectionName + " | "+connectorFrom+" TO "+moduleFrom+ " | "+connectorTo+" TO "+moduleTo+" L="+connectionLenght+" /"+connectionColor+" A="+wireArea+"',\"" + moduleFrom + "\",\"" + moduleTo + "\");");
        }else
            if (!connectorFrom.equals("") && connectorTo.equals("")) {
                tsl.add("TestConnection('" + connectionName + " | "+connectorFrom+" TO "+moduleFrom+" L="+connectionLenght+" /"+connectionColor+" A="+wireArea+"',\"" + moduleFrom + "\",\"" + moduleTo + "\");");
            }else
                if (connectorFrom.equals("") && !connectorTo.equals("")) {
                    tsl.add("TestConnection('" + connectionName + " | "+connectorTo+" TO "+moduleTo+" L="+connectionLenght+" /"+connectionColor+" A="+wireArea+"',\"" + moduleFrom + "\",\"" + moduleTo + "\");");
                }
    }

}
